Added support for creating an internal load balancer
schubergphilis/terraform-aws-mcaf-fargate pull request #25
Opened 2020-11-03 15:11 UTC by sbp-mbaan

2020-11-03 15:40 UTC, borisroman commented on lb.tf
>    subnets            = var.public_subnet_ids
this one?

2020-11-03 15:46 UTC, sbp-mbaan commented on lb.tf
>    subnets            = var.public_subnet_ids
Forgot to save the file.. 🤔

2020-11-03 16:10 UTC, svanharmelen requested changes
In my opinion this breaks the existing behavior.

2020-11-03 16:12 UTC, svanharmelen commented on variables.tf
> +  description = "List of subnet IDs assigned to ESC cluster"
```suggestion
  description = "List of subnet IDs assigned to ECS cluster"
```

2020-11-03 18:22 UTC, svanharmelen approved these changes

2020-11-03 22:38 UTC, borisroman approved these changes

2020-11-03 22:38 UTC, merged

2020-11-05 21:29 UTC, TommyM commented on variables.tf
> +variable "load_balancer_internal" {
I also like load_balander better. But there was already a variable called loadbalancer_eip it seems. The difference is really triggering 😂