EIPs are only allowed for Network Load Balancers
schubergphilis/terraform-aws-mcaf-fargate pull request #33
Opened 2021-03-11 16:34 UTC by lassebenni

Currently
```
module "fargate" {
  source = "github.com/schubergphilis/terraform-aws-mcaf-fargate?ref=v0.8.5"

  ...
  load_balancer_eip                   = true
  protocol                             = "HTTP" # default in module
  ...
}
```

Will result in 
<img width="1419" alt="afbeelding" src="https://user-images.githubusercontent.com/7990862/110928859-a16a6600-8327-11eb-8b3a-31239bc1d9a8.png">

Because the combination of protocol "HTTP" (default value for `var.protocol`) will result in a Application Load Balancer and assigning a EIP is only allowed for a Network Load Balancer as per https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateLoadBalancer.html:
> [Application Load Balancers] You must specify subnets from at least two Availability Zones. You cannot specify Elastic IP addresses for your subnets. 
> [Network Load Balancers] You can specify subnets from one or more Availability Zones. You can specify one Elastic IP address per subnet if you need static IP addresses for your internet-facing load balancer.

Proposed change: explicitely state that the protocol has to be `"TCP"` when `load_balancer_eip` is used.

2021-03-14 20:13 UTC, shoekstra requested changes
Hey @lassebenni, small change requested.

Thanks!
Stephen

2021-03-14 20:13 UTC, shoekstra commented on variables.tf
> +  description = "Whether to create Elastic IPs for the load balancer (only supported when protocol == 'TCP')"
```suggestion
  description = "Whether to create Elastic IPs for the load balancer (when `var.protocol` is `TCP`)"
```

2021-03-15 12:54 UTC, lassebenni commented
Thanks for the suggestion @shoekstra

2021-03-23 10:00 UTC, lassebenni commented
@shoekstra I made the changes you suggested, can you take a look again?

2022-04-11 20:18 UTC, svanharmelen commented
Is this one going to updated and merged? Or should we close and delete it?

2023-04-05 13:36 UTC, svanharmelen approved these changes
I just noticed this feedback request, so here you go 🙈

2025-06-13 10:30 UTC, closed without merging